### ISSUE TITLE
能否考虑增加referrer policy以支持防盗链的图床

### ISSUE THREAD

**Issue by THU-Pieris** [YieldRay/Random-Picture#4]
我的很多图存在新浪图床/B站图床上，如果请求带有referrer的话会返回403。或许能在php代码里添加`header('Referrer-Policy: no-referrer')`以支持这类防盗链的图床？或者在readme里提示一下使用者？感谢！

**Comment by YieldRay** [comment]
程序做的是302跳转，理论上对图床链接和api会用相同的请求。建议是html的head标签内添加
```html
<meta name=”referrer” content=”no-referrer” />
```
或者对每个图片使用
```html
<img src=”https://ws3.sinaimg.cn/thumb150/xxoo.jpg” referrerpolicy=”no-referrer”>
```
参考[这里](https://51.ruyo.net/12432.html#6)  
也可以启用api的`?raw`选项由api进行反代，例如<https://rand.deno.dev/?raw>

> 我的很多图存在新浪图床/B站图床上，如果请求带有referrer的话会返回403。或许能在php代码里添加`header('Referrer-Policy: no-referrer')`以支持这类防盗链的图床？或者在readme里提示一下使用者？感谢！

**Comment by YieldRay** [comment]
其实我不怎么懂php，哈哈

**Comment by THU-Pieris** [comment]
> 程序做的是302跳转，理论上对图床链接和api会用相同的请求。建议是html的head标签内添加
> 
> ```
> <meta name=”referrer” content=”no-referrer” />
> ```
> 
> 或者对每个图片使用
> 
> ```
> <img src=”https://ws3.sinaimg.cn/thumb150/xxoo.jpg” referrerpolicy=”no-referrer”>
> ```
> 
> 参考[这里](https://51.ruyo.net/12432.html) 也可以启用api的`?raw`选项由api进行反代，例如https://rand.deno.dev/?raw

感谢回复！您说的几个方法我都试过，但它们有其他副作用（法1）、太麻烦（法2）、有性能损失（法3）。我完全不懂php，自己瞎改了一下之后确实能用了，改之前会返回403. 我把我的改动贴到这里吧，以供也许有需要的人参考 https://github.com/THU-Pieris/Random-Picture/commit/1fb6128177c343789042b483f7aea21584142fea

总之再次感谢，这个issue就关闭了！

**Comment by YieldRay** [comment]
> > 程序做的是302跳转，理论上对图床链接和api会用相同的请求。建议是html的head标签内添加
> > ```
> > <meta name=”referrer” content=”no-referrer” />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 或者对每个图片使用
> > ```
> > <img src=”https://ws3.sinaimg.cn/thumb150/xxoo.jpg” referrerpolicy=”no-referrer”>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 参考[这里](https://51.ruyo.net/12432.html) 也可以启用api的`?raw`选项由api进行反代，例如https://rand.deno.dev/?raw
> 
> 感谢回复！您说的几个方法我都试过，但它们有其他副作用（法1）、太麻烦（法2）、有性能损失（法3）。我完全不懂php，自己瞎改了一下之后确实能用了，改之前会返回403. 我把我的改动贴到这里吧，以供也许有需要的人参考 [THU-Pieris@1fb6128](https://github.com/THU-Pieris/Random-Picture/commit/1fb6128177c343789042b483f7aea21584142fea)
> 
> 总之再次感谢，这个issue就关闭了！

看了文档我觉得`Referrer-Policy`是浏览器给服务器的请求头，所以感觉给浏览器发这个header应该没用吧  
但是如果有效的话，可以这样修改
```php
// php代码的最后几行
} else {
    header('Referrer-Policy: no-referrer'); // 添加在这里
    header('Location: ' . $imgs_array[$id]);
}

exit();
```
对于deno版本
```ts
return new Response(null, {
    status: 302,
    headers: {
        location: remoteURL,
        "cache-control": "no-cache",
        "Referrer-Policy": "no-referrer", // 这里添加
    },
});
```

**Comment by YieldRay** [comment]
因为一般用的都是公开的图床，对于有反盗链的图床并没有测试过

**Comment by THU-Pieris** [comment]
> > > 程序做的是302跳转，理论上对图床链接和api会用相同的请求。建议是html的head标签内添加
> > > ```
> > > <meta name=”referrer” content=”no-referrer” />
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 或者对每个图片使用
> > > ```
> > > <img src=”https://ws3.sinaimg.cn/thumb150/xxoo.jpg” referrerpolicy=”no-referrer”>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 参考[这里](https://51.ruyo.net/12432.html) 也可以启用api的`?raw`选项由api进行反代，例如https://rand.deno.dev/?raw
> > 
> > 
> > 感谢回复！您说的几个方法我都试过，但它们有其他副作用（法1）、太麻烦（法2）、有性能损失（法3）。我完全不懂php，自己瞎改了一下之后确实能用了，改之前会返回403. 我把我的改动贴到这里吧，以供也许有需要的人参考 [THU-Pieris@1fb6128](https://github.com/THU-Pieris/Random-Picture/commit/1fb6128177c343789042b483f7aea21584142fea)
> > 总之再次感谢，这个issue就关闭了！
> 
> 看了文档我觉得`Referrer-Policy`是浏览器给服务器的请求头，所以感觉给浏览器发这个header应该没用吧 但是如果有效的话，可以这样修改
> 
> ```
> // php代码的最后几行
> } else {
>     header('Referrer-Policy: no-referrer'); // 添加在这里
>     header('Location: ' . $imgs_array[$id]);
> }
> 
> exit();
> ```
> 
> 对于deno版本
> 
> ```ts
> return new Response(null, {
>     status: 302,
>     headers: {
>         location: remoteURL,
>         "cache-control": "no-cache",
>         "Referrer-Policy": "no-referrer", // 这里添加
>     },
> });
> ```

按照您的方法改动了，确实可以，谢谢！作为对比，我把改动前后的vercel deployment放在这里：
改动前： https://random-picture-9cpdp7k0c-pieris05.vercel.app
改动后： http://random-picture-bw5sp6vve-pieris05.vercel.app

（用反盗链的图床一是因为历史原因（新浪突然就反盗链了，懒得迁移了），二是免费的图床不太好用，又不想付费QAQ
