### ISSUE TITLE
vercel版本不支持二级目录的api调用吧

### ISSUE THREAD

**Issue by arleycn** [YieldRay/Random-Picture#5]
试了下，想添加一个移动端的，比如
https://random-picture.vercel.app/moapi/
,发现直接404了，官方文档也没找到

**Comment by YieldRay** [comment]
> 试了下，想添加一个移动端的，比如 https://random-picture.vercel.app/moapi/ ,发现直接404了，官方文档也没找到

php的文档在这里<https://github.com/juicyfx/vercel-php>

**Comment by YieldRay** [comment]
```json
{
  "functions": {
    "api/*.php": {
      "runtime": "vercel-php@0.5.0"
    }
  }
}
```

**Comment by arleycn** [comment]
感谢
